name: Build Pack
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build Resourcepack
    steps:
      - uses: actions/zipup@v1.0.1
        with:
          files: '["packs/**", "pack.mcmeta"]'
          out-path: 'pack.zip'
