name: Build Pack
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Resourcepack
    steps:
      - uses: MinecraftPlusGang/ZipUp@v1.0.5
        with:
          files: '["packs/**", "pack.mcmeta"]'
          out-path: 'pack.zip'
