name: Build Pack
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/zipup@v1.0.1
        with:
          files: '["packs/**", "pack.mcmeta"]'
          out-path: 'pack.zip'
